### ISSUE TITLE
TODO: Winning Detection

### ISSUE THREAD

**Issue by roryclaasen** [roryclaasen/AngularTicTacToe#2]
- [x] Move result board to server
	- [x] Result board checking to server
- [x] Implement Winner Check on server
	- [x] Send results to client

**Comment by roryclaasen** [comment]
Completedas of 4c830531ab1a9178ff7b753f7b7ae7877820c8ae
